"""user status, login_dt and created_dt

Revision ID: 624ce5894e13
Revises: 2cf780642f74
Create Date: 2024-09-30 11:41:55.243713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624ce5894e13'
down_revision = '2cf780642f74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('login_dt', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_dt', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_dt')
        batch_op.drop_column('login_dt')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
